project:
  type: website
  output-dir: docs
website:
  title: "Drydan's Portfolio"

  sidebar:
    logo: "images/pfp.png"
    pinned: true
    align: center
    style: "docked"
    contents: 
      - href: index.qmd
        text: Welcome
      - section: posts-hockey/index.qmd
        contents: 
          - href: posts-hockey/player-positions/index.qmd
            text: Player Positions
          - href: posts-hockey/rapm/index.qmd
            text: RAPM Models
      - href: posts-misc/yachtdice/index.qmd
        text: Yacht Dice
      - section: posts-misc/index.qmd
        contents:
          - posts-misc/pipelines/index.qmd

      

format:
  html:
    theme: cosmo
    css: styles.css


